In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

cleaned_1 = pd.read_csv('../data/cleaned_data/tracks_tagged_modified_041025.csv')
cleaned_2 = pd.read_csv('../data/cleaned_data/tracks_tagged_modified_041225.csv')
cleaned_3 = pd.read_csv('../data/cleaned_data/tracks_tagged_v4.csv')

print(f"Length of cleaned_1: {len(cleaned_1)}")
print(f"Length of cleaned_2: {len(cleaned_2)}")
print(f"Length of cleaned_3: {len(cleaned_3)}")

Length of cleaned_1: 9013
Length of cleaned_2: 9013
Length of cleaned_3: 4366

In [8]:
cleaned_3.head()

,id_track,id_site,id_m2,source,duration,alarm,min_speed,max_speed,avg_speed,curviness,...,repairs,distress,other,miss_ais,violation,le_contact,tdate,ttime,type_m2_agg,activity
0,29980760,10,18-0704-1000,radar,637,0,7.1,14.4,10.636634,1.023164,...,0,0,0,0,0,0,2023-07-04,10:06:47,NaN,work
1,30278317,10,158-0714-0950,radar,5463,1,0.1,6.7,3.016000,2.591425,...,0,0,0,0,0,0,2023-07-14,10:45:04,sail,drifting
2,30281714,10,196-0714-1032,radar,572,0,0.1,2.1,0.694318,1.300154,...,0,0,0,0,0,0,2023-07-14,10:43:06,NaN,NaN
3,30282211,10,1-0714-1040,radar,581,0,4.0,26.5,12.441758,1.068525,...,0,0,0,0,0,0,2023-07-14,10:42:50,NaN,work
4,31250251,10,63-0811-1036,radar,1379,1,0.7,13.7,10.932418,1.034715,...,0,0,0,0,0,0,2023-08-11,10:43:51,fishing_boat,transit